version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: sudachen/go1127-ci

    parallelism: 1

    environment: # environment variables for the build itself
      CC_TEST_REPORTER_ID: e45a96f3f2a7e7da3500b6949304061197e54ca24984bb6784c1b2ec01cdfb40

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      - restore_cache: # restores saved cache if no changes are detected since last run
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      - run: make build

      - run: make run-tests

      - run: mkdir -p github.com/sudachen &&
             ln -s $(pwd) github.com/sudachen/coin-exchange &&
             /usr/local/bin/cc-test-reporter after-build

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build